<a href="https://colab.research.google.com/github/S-JT/DSEA-CAPSTONE-PROJECT/blob/main/CAPSTONE_PROJECT_SCRAPING_CODE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import time
import datetime

In [ ]:
products = []
for i in range(1,5):
  url =  f"https://textbookcentre.com/catalogue/on-sale/?sort_by=popularity&items_per_page-"
  headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}
  response = requests.get(url)
  soup = BeautifulSoup(response.text, 'html.parser')

  titles = soup.find_all(class_='card-title product-card-name')
  product_titles = [title.text.strip() for title in titles]
  p1 = soup(class_='stockrecord-price-current')
  product_price = [p1.text.strip() for p1 in p1]
  p2 = soup(class_='stockrecord-price-old')
  previous_price = [p2.text.strip() for p2 in p2]
  sale = soup(class_='product-ribbon-sale')
  sale_discount = [sale.text.strip() for sale in sale]

  Links = soup.find_all('a', attrs={'class':'/catalogue/lenovo-loq-3-gaming-series-i5-8gb-512gb-ssd-rtx2050-4gb-win-11-156_371085/'})
  Links_list = []
  #loop for extracting links from products
  for Link in Links:
    Links_list.append(Link.get('href'))
     #create a dictionary
  d = {"product_titles":[], "product_price":[], "previous_price":[], "sale_discount":[]}
  #loop to extract product details from each link
  for Link in Links_list:
    new_response = requests.get("https://textbookcentre.com/catalogue/category/books/?page=71" + Link, headers)
    new_soup = BeautifulSoup(new_response.content, "html.parser")

#use functions to display the necessary product information
d['product_titles'].append(product_titles)
d['product_price'].append(product_price)
d['previous_price'].append(previous_price)
d['sale_discount'].append(sale_discount)

final_df = pd.DataFrame.from_dict(d)
final_df['product_titles'].replace('', np.nan,inplace=True)
final_df = final_df.dropna(subset=['product_titles'])
final_df.to_csv("final_data.csv", header=True, index=False)

import csv
header = ['product name', 'Current price', 'previous price', 'Discount %']
data = [product_titles, product_price, previous_price, sale_discount]

with open('final_data.csv"', 'w+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerow(data)

    #Now we are appending data to the csv

with open('final_data.csv', 'a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

import pandas as pd

df = pd.read_csv(r'/content/final_data.csv')

In [ ]:
df.head()

,product_titles,product_price,previous_price,sale_discount
0,"['Storymoja: My Reading Diary Level 1', 'Lenov...","['KES 350', 'KES 149,500', 'KES 169,100', 'KES...","['KES 480', 'KES 157,500', 'KES 178,000', 'KES...","['27% Off', '5% Off', '5% Off', '23% Off', '4%..."
1,"['Storymoja: My Reading Diary Level 1', 'Lenov...","['KES 350', 'KES 149,500', 'KES 169,100', 'KES...","['KES 480', 'KES 157,500', 'KES 178,000', 'KES...","['27% Off', '5% Off', '5% Off', '23% Off', '4%..."

In [ ]:
df.dtypes

product_titles    object
product_price     object
previous_price    object
sale_discount     object
dtype: object